version: '3'
services:
  postgresql-database:
    image: postgres
    networks:
      - trains-network
    ports:
      - '15432:5432'
    environment:
      POSTGRES_DB: trains
      POSTGRES_USER: trains
      POSTGRES_PASSWORD: trains_pass
      POSTGRES_INITDB_ARGS: "-E=UTF8 --lc-collate=C --lc-ctype=C"

  trains-application:
    environment:
      - PSQL_DB_URL=jdbc:postgresql://postgresql-database:5432/trains
    build:
      context: Backend
    ports:
      - '8080:8080'
    networks:
      - trains-network
    depends_on:
      - postgresql-database


networks:
  trains-network:
    driver: bridge
