spring:
  datasource:
    password: trains_pass
    username: trains
    url: jdbc:postgresql://localhost:15432/trains
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: update

    serialization:
      write_dates_as_timestamps: false
  security:
    thymeleaf:
      cache: false

  liquibase:
    enabled: false
  endpoints:
    web:
      exposure:
        include: health,prometheus,info,metric
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true

server:
  port: 8080
  error:
    include-message: always
